### ISSUE TITLE
Trackpad Issue after Chinese Trackpad Firmware Update: Fixed!

### ISSUE THREAD

**Issue by bertiepeek** [Azkali/GPD-P2-MAX-Hackintosh#1]
If you have installed the trackpad firmware update it will cause the trackpad to behave erratically in MacOS - you can restore the firmware to its original version with the attached firmware installer from the manufacturer. (Credit goes to Gabe87 @ InsanelyMac.)

[GPD P2 MAX触控板固件_61119092.zip](https://github.com/Azkali/GPD-P2-MAX-Hackintosh/files/3767374/GPD.P2.MAX._61119092.zip)

**Comment by Azkali** [comment]
Closing as I've attached the trackpad driver inside this repo, will credit @Gabe87 and update the README
