### ISSUE TITLE
Touchpad not working in 10.15.1

### ISSUE THREAD

**Issue by feyeleanor** [Azkali/GPD-P2-MAX-Hackintosh#14]
I've a GPD P2 Max (Batch 2 | BIOS 0.25) which is running really nicely under macOS 10.15.1 except for the touchpad which is non-responsive.

I've tried the keyboard firmware downgrade with the driver included in the repo and the software indicated success but the result was an unresponsive keyboard even after hard reboots. I've restored the newer keyboard firmware and am using a bluetooth mouse.

A couple of things I've noted.

1. when running the macOS installer (prepared as per suggested) the trackpad works but controls the absolute mouse position not its relative position

2. even though the trackpad does't work in my installed copy of 10.15.1, if the screen dims and I touch the trackpad the screen brightens up again

3. the keyboard is listed in System Information as Product ID: 0x0020, Vendor ID: 0x258a, version 1.0

4. the mouse pointer is visible in the clover boot loader but doesn't respond to trackpad movement

**Comment by andot** [comment]
see #1 and #3

**Comment by Azkali** [comment]
Is your issue solved @feyeleanor ?

**Comment by feyeleanor** [comment]
I've already tried those steps (see my second paragraph) and they left me with a non-functioning keyboard.

**Comment by Azkali** [comment]
Maybe you could try to address this issue directly to GPD, **might be** an issue with your specific device ( hope not ) as no other user has this issue

**Comment by feyeleanor** [comment]
If anything changes with system updates I'll let you know. For now though I've picked up an Apple Magic Trackpad which works very nicely.

**Comment by Azkali** [comment]
Closing for now will reopen this issue if anyone encounters the same problem

**Comment by jadehsn** [comment]
I’m running into this issue as well.

**Comment by feyeleanor** [comment]
Since I upgraded to 10.15.3 my trackpad occasionally responds but there doesn't appear to be any pattern to when and I've no idea how to grab useful logging or debugging info.

**Comment by sunsmoke** [comment]
I also have this issue as far as the installer goes. If I just tap the touchpad, the mouse pointer moves to that absolute position on screen. It's difficult, if not impossible to click items in the menubar. I have not gotten past the install yet. I am on BIOS 0.29, using mojave 10.14.6 security update 2020-002.
update: After the install completed, macos appears to be working okay for the most part, but the touchpad is still doing the absolute positioning thing.

**Comment by sunsmoke** [comment]
I tried a 10.15.5 installer with the same clover/efi as I used to install 10.14.6 above. I just booted into the recovery/installer only. It looked good, except that the touchpad was nonresponsive. USB mouse worked fine. I didn't try to install the os.
If there's any logging I can get from 10.14 system that you need, let me know. I also don't mind trying test versions or configs.
Thanks for all your hard work, Azkali.

**Comment by jswxwxf** [comment]
HI, I’m running into this issue as well.
Now my keyboard is totally non-functioning.
Can you tell me how you restored the newer keyboard firmware without a functioning keyboard？

**Comment by jswxwxf** [comment]
Anyone here？ I need help~
