### ISSUE TITLE
Change hidden CFG Lock setting

### ISSUE THREAD

**Issue by andot** [Azkali/GPD-P2-MAX-Hackintosh#16]
https://www.tonymacx86.com/threads/successfully-patched-z170x-ud5-th-cfg-lock-msr-ex02.253466/page-2#post-1847437

GPD P2 Max:
```
0x285A1 	Form: View/Configure CPU Lock Options, FormId: 0x2738 {01 86 38 27 CC 01}
0x285A7 		One Of: CFG Lock, VarStoreInfo (VarOffset/VarName): 0x587, VarStore: 0x1, QuestionId: 0x154, Size: 1, Min: 0x0, Max 0x1, Step: 0x0 {05 91 9A 03 9B 03 54 01 01 00 87 05 10 10 00 01 00}
0x285B8 			One Of Option: Disabled, Value (8 bit): 0x0 {09 07 04 00 00 00 00}
0x285BF 			One Of Option: Enabled, Value (8 bit): 0x1 (default) {09 07 03 00 30 00 01}
0x285C6 		End One Of {29 02}
0x285C8 		One Of: Overclocking Lock, VarStoreInfo (VarOffset/VarName): 0x636, VarStore: 0x1, QuestionId: 0x155, Size: 1, Min: 0x0, Max 0x1, Step: 0x0 {05 91 96 03 97 03 55 01 01 00 36 06 10 10 00 01 00}
0x285D9 			One Of Option: Disabled, Value (8 bit): 0x0 (default) {09 07 04 00 30 00 00}
0x285E0 			One Of Option: Enabled, Value (8 bit): 0x1 {09 07 03 00 00 00 01}
0x285E7 		End One Of {29 02}
0x285E9 	End Form {29 02}
```

```
setup_var_3 0x587 0x00
```

**Comment by Azkali** [comment]
@andot Setting `setup_var_3 0x587 0x00` does not update it in current bios, how did you manage to save it onto your bios ?

**Comment by andot** [comment]
1. Create a GUID partition map usbdisk.

![image](https://user-images.githubusercontent.com/232161/70874845-ef8e9d80-1fee-11ea-9427-ad911b5cf173.png)

2. Download and put Grub Shell on usb

* Download Grub Shell from [grub-mod-setup_var](https://github.com/datasone/grub-mod-setup_var/releases)
* Extract it into ~/Downloads folder
* Rename it from modGRUBShell.efi to bootx64.efi
* Copy bootx64.efi into USB disk

```
cd /Volumes/EFIBOOT
ls
mkdir -p /Volumes/EFIBOOT/EFI/BOOT
cp -iR ~/Downloads/bootx64.efi /Volumes/EFIBOOT/EFI/BOOT/bootx64.efi
```

![image](https://user-images.githubusercontent.com/232161/70874923-32e90c00-1fef-11ea-8c8d-6ff10102281e.png)

3. boot with this usbdisk into grub.

4. run `setup_var_3 0x587 0x00`

5. run `reboot` to reboot your computer.

and then you will find CFG Lock is disabled.

```
MSR_PMG_CST_CONFIG_CONTROL........(0xE2) : 0x7E000008
------------------------------------------
 - I/O MWAIT Redirection Enable......... : 0 (not enabled)
 - CFG Lock............................. : 0 (MSR not locked)
 - C3 State Auto Demotion............... : 1 (enabled)
 - C1 State Auto Demotion............... : 1 (enabled)
 - C3 State Undemotion.................. : 1 (enabled)
 - C1 State Undemotion.................. : 1 (enabled)
 - Package C-State Auto Demotion........ : 1 (enabled)
 - Package C-State Undemotion........... : 1 (enabled)
```

After that. you can change the config.plist:

```xml
		<key>AppleIntelCPUPM</key>
		<true/>
		<key>AppleRTC</key>
		<true/>
		<key>KernelCpu</key>
		<false/>
		<key>KernelLapic</key>
		<false/>
		<key>KernelPm</key>
		<true/>
```

to be

```xml
		<key>AppleIntelCPUPM</key>
		<false/>
		<key>AppleRTC</key>
		<true/>
		<key>KernelCpu</key>
		<false/>
		<key>KernelLapic</key>
		<false/>
		<key>KernelPm</key>
		<false/>
```

to enable native power management.

**Comment by andot** [comment]
It can work on 0.24, 0.25 and 0.27 bios.

[0.27 bios.txt](https://github.com/Azkali/GPD-P2-MAX-Hackintosh/files/3965864/0.27.bios.txt)
[0.24 bios.txt](https://github.com/Azkali/GPD-P2-MAX-Hackintosh/files/3965865/0.24.bios.txt)

**Comment by Azkali** [comment]
Did exactly that but that doesn't seem to update anything, is it supposed to show new entries under BIOS ?
Edit: Never-mind I finally got it setup thanks, will add a section in the README with a big warning could you also update the chinese README ?

**Comment by Azkali** [comment]
Closing, will add a section inside README

**Comment by andot** [comment]
This is a hidden setting, we can't see it under BIOS.

**Comment by Azkali** [comment]
Where could I contact you directly to discuss about this repo ?

**Comment by Azkali** [comment]
I manage to tweak DVMT allocation with my BIOS unlocked thanks to your guide and a user from the GPD Discord.

But I'm now missing the battery status did you encountered this issue ?
If so and you happen to have a solution, could you make a pull request to fix that, it would be greatly appreciated !

Do you have discord so we can discuss about this repository ?

**Comment by andot** [comment]
There is no problem of battery status of my GPD p2 Max.
My GPD p2 Max is Batch 2 | BIOS 0.25 MacOS 10.15.2
![image](https://user-images.githubusercontent.com/232161/72779636-93571300-3c57-11ea-95cc-6f9080880465.png)
