### ISSUE TITLE
Screen brightness fix not working in 10.15.1

### ISSUE THREAD

**Issue by kaveshan1** [Azkali/GPD-P2-MAX-Hackintosh#19]
Hey guys,
Screen brightness fix as posted here doesn't seem to work in 10.15.1. Please help!

**Comment by Azkali** [comment]
Do you have a second barch GPD P2 MAX ?

If so then inside  `CLOVER -> ACPI -> patched` remove `DSDT.aml` and rename `DSDT_2.aml` as `DSDT.aml`

**Comment by kaveshan1** [comment]
I have the second batch and have renamed the above file with the issue ongoing. 

bios is 0.24

**Comment by Azkali** [comment]
Have you tried this #9

**Comment by Azkali** [comment]
Try the new SSDT-PNLF-0.27 renaming it SSDT-PNLF.aml and remove your current one

**Comment by kaveshan1** [comment]
You're an absolute legend!!! It worked. Thanks so much
