### ISSUE TITLE
bluetooth and usb

### ISSUE THREAD

**Issue by digitxo** [Azkali/GPD-P2-MAX-Hackintosh#2]
Bluetooth issue ++ I can't connect to any devices, it only stays on "Connecting.." Devices are detected however, which is a good thing.

USB issue.         ++  Only one USB works at a time, if I try another one I get please connect a powersource

Please help!

**Comment by Azkali** [comment]
Should be resolved with latest commit, just replace your CLOVER/ACPI/patched/SSDT.aml
