### ISSUE TITLE
 拜读将 GPD P2 Max 变身为 Macbook Nano，自己制作启动盘无法启动，请支招

### ISSUE THREAD

**Issue by zengold** [Azkali/GPD-P2-MAX-Hackintosh#23]
拜读将 GPD P2 Max 变身为 Macbook Nano，自己制作启动盘无法启动，请支招
通过采用兄弟的方法，我的BIOS是0.27版 把EFI拷贝至U盘的EFI覆盖后，还是无法启动，卡在
![微信图片_20200308102806_爱奇艺](https://user-images.githubusercontent.com/25707360/76155502-ab132980-6127-11ea-8235-08256bc76a13.jpg)
请兄弟继续看看如何弄，或者可否网盘一个您已经ok安装完毕的版本。衷心感谢

**Comment by GuanJi-Cheng** [comment]
Your photos are too blurry to see what's wrong with you. And did you install Mac OS successfully by using U disk?And before you install the system successfully, you do not need to copy EFI to the U disk and overwrite the original EFI.

**Comment by zengold** [comment]
如果直接用u盘安装macos成功的话，那EFI覆盖是什么时候呢？谢谢

**Comment by zengold** [comment]
请问您有qq号，或者微信号码？我们加个朋友可好：？

**Comment by GuanJi-Cheng** [comment]
step 3:During first boot, after installing the OS, mount your EFI partition and place the CLOVER folder alongside other OSes bootloader

**Comment by zengold** [comment]
> step 3:During first boot, after installing the OS, mount your EFI partition and place the CLOVER folder alongside other OSes bootloader

hello bros，can you supply Macos able working to install images or usb storage ISO，i was create usb boot driver fail many times。thks！
