### ISSUE TITLE
Keyboard firmware restoration

### ISSUE THREAD

**Issue by jamilroach** [Azkali/GPD-P2-MAX-Hackintosh#24]
After flashing the Chinese keyboard to US firmware using the Hailuck tool how do we revert to the original HEX key? Thanks!

**Comment by Azkali** [comment]
You can use the official GPD US firmware here : http://www.gpd.hk/filedownload/31842

**Comment by jswxwxf** [comment]
Did it work？ I restored the official keyboard firmware but the keyboard is still not responding...
