### ISSUE TITLE
WiFi issue - possible driver solution included

### ISSUE THREAD

**Issue by Andiweli** [Azkali/GPD-P2-MAX-Hackintosh#27]
Regarding the issues with the "not working" Intel 7265 WiFi driver.
I've found a working solution here:
https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/330#issuecomment-641406975

I used the 3.8.1 driver, set it up via the included script.
Afterwards I added SSID and password via "Hackintool" - after a reboot everything works with internal WiFi. No single reboot so far, I charged my GPD twice so far. One charge lasts around 4 hours.

[
![IMG_1907](https://user-images.githubusercontent.com/11447150/84299196-a314bc80-ab50-11ea-85be-c8a093a3a959.jpeg)
](url)

**Comment by Azkali** [comment]
Thanks I'll add this ASAP !

**Comment by Azkali** [comment]
Closed in #36
