### ISSUE TITLE
MacOS Setup needs internet connection...

### ISSUE THREAD

**Issue by Andiweli** [Azkali/GPD-P2-MAX-Hackintosh#28]
...Catalina want's an internet connection.
But the P2 Max doesn't have a LAN connector - and WiFi doesn't work.
Any plans?

**Comment by Andiweli** [comment]
Solved it by using an offline Cataline installer.
https://hackintosher.com/guides/how-to-make-a-macos-10-15-catalina-flash-drive-installer/

**Comment by andot** [comment]
Here is the intel wifi driver: https://github.com/zxystd/itlwm
