### ISSUE TITLE
ACPI troubles - close display/ standby/ permanent fan

### ISSUE THREAD

**Issue by Andiweli** [Azkali/GPD-P2-MAX-Hackintosh#29]
I've set up with your scripts - so far everything's fine.
Even touchscreen and WiFi is working now!

**The only issues I have:**

**The fan is on permanently** - I have already set "quiet mode" and "battery saving" in BIOS, with no success. The fan blows like it's 100 degrees :-)

**When closing the display**, the background light and the fan still work. There's no sleep or standby for me. Any idea as it should work as "What works" says :_(

Thank you!

**Comment by Andiweli** [comment]
I tried inserting the "SSDT-SleepLID0.aml" into the EFI/ACPI/patched folder - then the display went out when closing it. But fan and OS are still working.
When I reopen the display, it stays out - regardless which button I am pressing.
I can only switch it off by long pressing the powerbutton.

So currently I am using the P2max hackintosh without the "SSDT-SleepLID0.aml".
I am on Catalina 10.5.5 and BIOS v0.29.

**Comment by Andiweli** [comment]
I've now experienced several different behaviours...

**Behaviour 1:**
Close display > wait approx. 20 seconds > fan switches off
Open display > fan switches on > after a few seconds display is on and functioning

**Behaviour 2:**
Close display > wait approx. 20 seconds > fan switches off
Open display > fan switches on > display stays dark and not working

**Behaviour 3:**
Close display > wait approx. 20 seconds > fan continues
Open display > device is still working and didn't switch off

I experienced this issues all in one session without powering down the device - except when behaviour 2 happens off course :-)

**Comment by Andiweli** [comment]
I think I've found an issue...

Close display > wait 20 seconds > devices goes to sleep only works ONCE (in a session).
If I open the display, enter my password and close it again afterwards, it keeps powered on.

It only works again if I power the GPD down.

**Comment by Azkali** [comment]
ACPI patch need some rework
