### ISSUE TITLE
Touchpad - guidance/how?

### ISSUE THREAD

**Issue by clotted** [Azkali/GPD-P2-MAX-Hackintosh#3]
My GPD P2 Max (Batch 2 | BIOS 0.25) touchpad is non responsive in macOS 10.15.1.

Readme says "TouchPad ( 20190919 Chinese keyboard firmware will cause problems, use the file driver inside touchpad_driver to downgrade )"

The ZIP contains a Windows exe, a hex file, and a PDF which shows steps completed on Windows (am lost/confused)
Can you provide guidance on what/how/where to install the touchpad driver/kext?

**Comment by Azkali** [comment]
You should install the touchpad driver within Windows
