### ISSUE TITLE
Intel 615 graphics has occasional stutter

### ISSUE THREAD

**Issue by Andiweli** [Azkali/GPD-P2-MAX-Hackintosh#30]
I now installed some games on Catalina on the P2 Max...

- Diablo III - occasional stutter everytime the player moves
- Farming Simulator 2017 - occasional stutter every few seconds

I already set the resolution to 1280x800 and/or lower.
Also set details lower or lowest. 
Still the same stutter. 

Any idea?

**Comment by Azkali** [comment]
Hi, I will try to test it soon. And try to reproduce this issue.

**Comment by Andiweli** [comment]
> Hi, I will try to test it soon. And try to reproduce this issue.

Thanks.
If it helps, I am on Catalina 10.5.5 and BIOS v0.29.

**Comment by Azkali** [comment]
What is the state of this issue with the latest commit ?

**Comment by Andiweli** [comment]
Seems solved to me.
