### ISSUE TITLE
Battery status different between system and CoconutBattery

### ISSUE THREAD

**Issue by Andiweli** [Azkali/GPD-P2-MAX-Hackintosh#31]
Hi there
I don't know which program reads the wrong percentage... :-)
System battery shows 88% while CoconutBattery shows 84%.
After restart it still differs 4%.

I had to use DSDT_2 because the default DSDT didn't show anything.

I am on Catalina 10.5.5 and BIOS v0.29.
Any idea? Thanks.

<img width="522" alt="Bildschirmfoto 2020-06-11 um 18 55 03" src="https://user-images.githubusercontent.com/11447150/84417253-a2922980-ac15-11ea-8fad-f849a9f67538.png">

**Comment by Azkali** [comment]
Can you try to pull the latest changes ( removing what's not needed anymore, updating what has been updated with the latest commit ) and see if helps ?
