### ISSUE TITLE
touchpad in absolute mode

### ISSUE THREAD

**Issue by sunsmoke** [Azkali/GPD-P2-MAX-Hackintosh#35]
macos 10.14.6, bios 0.29 My touchpad was in absolute mode during install, and after booting the installed system. 
I am only opening this because the touchpad is not usable in absolute mode, and there's no setting (that I'm aware of) to fix this.
This might be related to this ticket: https://github.com/Azkali/GPD-P2-MAX-Hackintosh/issues/14

**Comment by sunsmoke** [comment]
update: I've been on this keyboard firmware: http://www.gpd.hk/filedownload/31842
GPD's site describes it: "GPD P2 Max Keyboard Firmware Update (English)" and "Support Microsoft Precision TouchPad (PTP) mode"

I remember this dramatically changing the behavior of the touchpad under windows, and making it somewhat better under Linux.

Please let me know if there's another firmware I can use to make this work. Can I safely use the firmware already checked into this project in "touchpad_driver" ?

Further, macos doesn't see the touchpad as a touchpad. When I look in system prefs, it tells me that there are no trackpads installed, even though touching it moves the pointer to absolute positioning.

**Comment by andot** [comment]
touchpad as a mouse. touchscreen as a trackpad.
