### ISSUE TITLE
The latest compiled WiFi driver and client

### ISSUE THREAD

**Issue by andot** [Azkali/GPD-P2-MAX-Hackintosh#39]
[HeliPort-itlwm-itlwmx-0718.zip](https://github.com/Azkali/GPD-P2-MAX-Hackintosh/files/4941773/HeliPort-itlwm-itlwmx-0718.zip)

I tested it to work on Mac OS 10.15.5 and 10.15.6.

![image](https://user-images.githubusercontent.com/232161/87854235-1de8a880-c943-11ea-8780-38efe598c750.png)
![image](https://user-images.githubusercontent.com/232161/87854247-2fca4b80-c943-11ea-9fd5-903e21d5503d.png)

**Comment by jschaeke** [comment]
I was curious what this was about. I tried it, had to remove itlwmx in order to boot. Heliport now has a Launch at login option. What is the difference between the two kexts in it?

**Comment by andot** [comment]
itlwmx is a wifi6 driver for ax200. we don't need it.

**Comment by jschaeke** [comment]
Seems to be running ok here, so why it's an issue? Will you merge it into the master?

**Comment by jschaeke** [comment]
Although I must confess this and previous versions of the wifi driver are giving sometimes slow/unreliable connections and connecting to an AP takes a couple of attempts (wifi off/on). I had also problems in Linux so it can be my wifi-card is a bad.
