### ISSUE TITLE
new SSDT didn't fix issue

### ISSUE THREAD

**Issue by digitxo** [Azkali/GPD-P2-MAX-Hackintosh#4]
still can't connect Bluetooth devices, it says connected then disconnects

**Comment by Azkali** [comment]
Which device are you trying to connect ?
I can successfully pair my phone, mouse, keyboard and mouse

**Comment by clotted** [comment]
AirPods Pro connect great 👍 
Logitech MX ANYWHERE 2S mouse shows up but fails to connect, so ordered a Unifying Receiver

**Comment by digitxo** [comment]
Hi. I just checked my Bluetooth speaker and it works, but my Logitech M585 isn't connecting!

**Comment by clotted** [comment]
FYI - Logitech Unifying Receiver with Logitech Options 8.02.86 is working great. Connects to my MX Anywhere 2S like a boss
