### ISSUE TITLE
键盘不认了

### ISSUE THREAD

**Issue by jswxwxf** [Azkali/GPD-P2-MAX-Hackintosh#41]
按照教程：

触摸板 ( 20190919 中文键盘固件会导致问题, 请在 Windows 下运行 touchpad_driver 文件夹中的固件驱动进行降级。credits : @Gabe87 from insanelymac )

刷了固件之后，键盘完全不认了怎么办……

**Comment by jswxwxf** [comment]
没有了键盘，连 BIOS 也进不去了，大神救命啊！！！

**Comment by jswxwxf** [comment]
After downgrading the keyboard firmware according to the tutorial, my keyboard is now totally non-functioning.
I want to reset the firmware, but without the keyboard, I cannot even access the BIOS.
Any idea to reset the keyboard firmware.

**Comment by jswxwxf** [comment]
Anyone here？ I need help~

**Comment by iamcheyan** [comment]
使用外置键盘能进到BIOS里吗？

**Comment by jswxwxf** [comment]
嗯，通过外置键盘，我尝试了以下方案：
1. 通过 WinPE 启动刷了这个键盘的最新固件，然后重启之后内置键盘还是不认
GPD P2 Max 中文键盘固件更新
支持 Microsoft Precision TouchPad (PTP)模式，带高级选项，可以自定义手指触摸方式。
http://www.softwincn.com/filedownload/134751
2. 重新刷回官方 Windows，然后内置键盘还是不认……
GPD P2 Max Windows 10（1909）多国语言版固件，支持“一键还原”（也适用于8100Y、3965Y处理器的 Pocket 2）
旧版机器需手动升级 P2 Max BIOS V0.29 版BIOS，才能更新此固件。关于BIOS，请切换到本页BIOS标签去下载
下载链接：http://download.softwincn.com/P2_P2MAX_1909_20200623-User-CN.zip

**Comment by jswxwxf** [comment]
算了，换新机了，我觉得下面这句话最好删掉，太害人了~

触摸板 ( 20190919 中文键盘固件会导致问题, 请在 Windows 下运行 touchpad_driver 文件夹中的固件驱动进行降级。credits : @Gabe87 from insanelymac )

**Comment by jswxwxf** [comment]
返回厂家换机了
