### ISSUE TITLE
hdmi、screentouch、sleep issue     视频输出、屏幕触摸、睡眠问题

### ISSUE THREAD

**Issue by yuyuyulin** [Azkali/GPD-P2-MAX-Hackintosh#42]
1.hdmi输出视频的时候，1080P显示器正常，测试2K显示器黑屏，网友反馈4K也无法正常显示（未亲测4K，无4K显示器）
for hdmi out, is working in 1080p mode,  not work in 2K or 4k mode.

2.屏幕触摸，用了efi，屏幕无触摸，也尝试了issue中的voodooi2c v2.3 and SSDT-TCSE.aml.zip ，还是无法触摸。不知道问题在哪儿。

3.睡眠问题，盒盖的时候，有时候能睡眠，有时候不能睡眠，看几率

**Comment by Hamoze** [comment]
Firstly, I want to thank Azkali and Andot for their huge effort 

Secondly, I'am also facing the same problem of the screen touch ,,, I'am not able to make it work. iam still new to hackintosh world

**Comment by yuyuyulin** [comment]
触摸问题已解决，不能触摸都是bios版本过低导致，升级bios到0.29即可 ，官网没有0.25的，不知道哪儿找0.25，有的小伙伴也可以分享下，看下是不是和EFI完美贴合。

HDMI不能2K及以上输出，期待有大牛处理下这个问题。。本本太小了 偶尔接大屏还是很有用的~

**Comment by andot** [comment]
不用找 0.25 的 bios。我现在也是升级到了 0.29。0.29 的更好用。

**Comment by yuyuyulin** [comment]
> 不用找 0.25 的 bios。我现在也是升级到了 0.29。0.29 的更好用。

大佬，有遇到过睡眠不能唤醒的情况么。发现经常睡眠后，按任何按键没反应，等很久多按按可能才能醒

**Comment by Hamoze** [comment]
> > 不用找 0.25 的 bios。我现在也是升级到了 0.29。0.29 的更好用。
> 
> 大佬，有遇到过睡眠不能唤醒的情况么。发现经常睡眠后，按任何按键没反应，等很久多按按可能才能醒

I do not have issue waking up from sleep , after upgrading bios to 0.29
However, the I'am not able to make touch screen to work

is there any tutorial that i can follow to fix this issue

**Comment by yuyuyulin** [comment]
> > > 不用找 0.25 的 bios。我现在也是升级到了 0.29。0.29 的更好用。
> > 
> > 
> > 大佬，有遇到过睡眠不能唤醒的情况么。发现经常睡眠后，按任何按键没反应，等很久多按按可能才能醒
> 
> I do not have issue waking up from sleep , after upgrading bios to 0.29
> However, the I'am not able to make touch screen to work
> 
> is there any tutorial that i can follow to fix this issue

我直接升级后就可以用了。你可以重新覆盖efi试试。。感觉和bios关系比较大··

**Comment by jiangjianxiao** [comment]
我bios是0.29 <del>直接用仓库的efi 触摸不行</del> 很奇怪, 触摸屏突然能工作了 系统偏好设置中的触控板也能设置了,不知道怎么发生的 

<del>typec hub也不能驱动, windows下是没有问题的</del> 这个划掉,我试了另外一个typec hub可以工作

4k 用typec-dp线试过,能显示,显示不正常, 强制到1080时, 屏幕闪烁,不能用

typec hub 外接hdmi 1080显示器时,合盖,充电状态内置屏幕不会关闭, 按正常的举止, 充电状态下合盖能关闭外屏

感觉休眠,外接显示器存在一些没有规律的问题,这部分搞定实用性应该很强

**Comment by Hamoze** [comment]
> 我直接升级后就可以用了。你可以重新覆盖efi试试。。感觉和bios关系比较大··

I updated bios to 0.29 and the touch screen works now ,, thank you very much for your help 👍
