### ISSUE TITLE
How to connect a 4K monitor?如何连接4K显示

### ISSUE THREAD

**Issue by wqianglxf** [Azkali/GPD-P2-MAX-Hackintosh#46]
很高兴发现这个项目。我购买了一台，通过你的项目，我成功用上了MacOS 10.15.7。但是连接到4K显示器时，无法正常使用。我希望可以用上4K.你可以更新下吗？谢谢
I'm glad to find this project. I bought one, and through your project, I successfully used MacOS 10.15.7. However, when connected to a 4K monitor, it does not work properly. I hope I can use 4K. Can you update it? thank you

**Comment by wqianglxf** [comment]
4K connection display is normal, not 4K resolution

**Comment by andot** [comment]
这个是 HDMI 接口本身不支持 4K@60Hz。即使是在 Windows 上，接 4K 显示器也只能在 4K@30Hz 下运行。

**Comment by wqianglxf** [comment]
> 这个是HDMI接口本身不支持4K @ 60Hz。甚至是在Windows上，接4K显示器也只能在4K @ 30Hz下运行。

感谢小马哥的回复，连接4K显示器时，显示是2560x1440，比较模糊。之前看到你用Type C转DP的方案，是否可行？

**Comment by zncs520** [comment]
0x876 0x02 即可开启外接4k完美显示

**Comment by wqianglxf** [comment]
> 0x876 0x02即可开启双向4k完美显示

可以分享下你的Config文件吗？wqianglxf@tom.com

**Comment by andot** [comment]
> > 0x876 0x02即可开启双向4k完美显示
> 
> 可以分享下你的Config文件吗？[wqianglxf@tom.com](mailto:wqianglxf@tom.com)

@zncs520 说的不是 config 文件，是修改 bios 设置。

可以参考这个：https://github.com/Azkali/GPD-P2-MAX-Hackintosh/issues/16

setup_var_3 0x876 0x02

是把默认的 DVMT Pre-Allocated 的值，从 32M 改为 64M。

**Comment by wqianglxf** [comment]
> > > 0x876 0x02即可开启双向4k完美显示
> > 
> > 
> > 可以分享下你的Config文件吗？[wqianglxf@tom.com](mailto:wqianglxf@tom.com)
> 
> @zncs520 说的不是 config 文件，是修改 bios 设置。
> 
> 可以参考这个：#16
> 
> setup_var_3 0x876 0x02
> 
> 是把默认的 DVMT Pre-Allocated 的值，从 32M 改为 64M。

我尝试了这个方法，setup_var_3 0x876 0x02
提示
offset 0x876 is: 0x01
setting offset 0x876 to 0x02
reboot后显示器依然还是2560*1440

**Comment by zncs520** [comment]
> > > > 0x876 0x02即可开启双向4k完美显示
> > > 
> > > 
> > > 可以分享下你的Config文件吗？[wqianglxf@tom.com](mailto:wqianglxf@tom.com)
> > 
> > 
> > @zncs520 说的不是 config 文件，是修改 bios 设置。
> > 可以参考这个：#16
> > setup_var_3 0x876 0x02
> > 是把默认的 DVMT Pre-Allocated 的值，从 32M 改为 64M。
> 
> 我尝试了这个方法，setup_var_3 0x876 0x02
> 提示
> offset 0x876 is: 0x01
> setting offset 0x876 to 0x02
> reboot后显示器依然还是2560*1440
> 我查看了Hackintool接口0x04类型是DP，是不是这个原因导致的

当然不是!!!你把AAPL,ig-platform-id 改成00001619 其他全部去掉即可

**Comment by wqianglxf** [comment]
> > > > > 0x876 0x02即可开启双向4k完美显示
> > > > 
> > > > 
> > > > 可以分享下你的Config文件吗？[wqianglxf@tom.com](mailto:wqianglxf@tom.com)
> > > 
> > > 
> > > @zncs520 说的不是 config 文件，是修改 bios 设置。
> > > 可以参考这个：#16
> > > setup_var_3 0x876 0x02
> > > 是把默认的 DVMT Pre-Allocated 的值，从 32M 改为 64M。
> > 
> > 
> > 我尝试了这个方法，setup_var_3 0x876 0x02
> > 提示
> > offset 0x876 is: 0x01
> > setting offset 0x876 to 0x02
> > reboot后显示器依然还是2560*1440
> > 我查看了Hackintool接口0x04类型是DP，是不是这个原因导致的
> 
> 当然不是!!!你把AAPL,ig-platform-id 改成00001619 其他全部去掉即可

测试无效！！！

**Comment by wqianglxf** [comment]
在上述的第2项中，我查看了4K显示器属性，可能与3840x2160@60刷新率有关，似乎要修改到30，但我在尝试修改到30时，内外屏同时黑屏，但能感觉电脑没有死机，还在运行，后来强制关机。我准备放弃了，期待大佬更新吧。。

**Comment by wqianglxf** [comment]
> > > 0x876 0x02即可开启双向4k完美显示
> > 
> > 
> > 可以分享下你的Config文件吗？[wqianglxf@tom.com](mailto:wqianglxf@tom.com)
> 
> @zncs520 说的不是 config 文件，是修改 bios 设置。
> 
> 可以参考这个：#16
> 
> setup_var_3 0x876 0x02
> 
> 是把默认的 DVMT Pre-Allocated 的值，从 32M 改为 64M。

小马哥，期待您的更新

**Comment by wqianglxf** [comment]
> 这个是 HDMI 接口本身不支持 4K@60Hz。即使是在 Windows 上，接 4K 显示器也只能在 4K@30Hz 下运行。

我用的是LG 27UL850尝试了好多次，这个原因很关键。

**Comment by wqianglxf** [comment]
![image](https://user-images.githubusercontent.com/66858128/103149534-389e3380-47a5-11eb-8738-f3f3cb2ef029.jpeg)
![image](https://user-images.githubusercontent.com/66858128/103149537-40f66e80-47a5-11eb-87b4-a839432319ac.jpeg)
果然是30hz的原因，我远程桌面修改后可以了，没有修改 AAPL,ig-platform-id 00001619。

**Comment by wqianglxf** [comment]
最后感谢 @zncs520 @andot 提示！

**Comment by andot** [comment]
@wqianglxf 怎么搞定的，我的 飞利浦 4K 显示器，现在接上去只能达到1080p，或者1080x2160这样一个奇怪分辨率。

**Comment by wqianglxf** [comment]
> @wqianglxf 怎么搞定的，我的 飞利浦 4K 显示器，现在接上去只能达到1080p，或者1080x2160这样一个奇怪分辨率。

搞定没有？小马哥，你的这种情况可能是EDID的问题。我只是修改0x876 to 0x02，还有输入了正确的EDID。但我用了分辩率修改软件，强制修改到4K@30hz。这个修改有可能在黑屏的情况下，所有我用远程桌面试的，后来成功了。

**Comment by andot** [comment]
> > @wqianglxf 怎么搞定的，我的 飞利浦 4K 显示器，现在接上去只能达到1080p，或者1080x2160这样一个奇怪分辨率。
> 
> 搞定没有？小马哥，你的这种情况可能是EDID的问题。我只是修改0x876 to 0x02，还有输入了正确的EDID。但我用了分辩率修改软件，强制修改到4K@30hz。这个修改有可能在黑屏的情况下，所有我用远程桌面试的，后来成功了。

嗯，确实跟 EDID 有关，昨天我把 EDID 改了一下，0x876 也改为了 0x02，然后装了 SwitchResX ，外接显示器之后，确实可以正常 4K@30Hz 显示了，本本自带的屏幕也可以用更高的 HiDPI 分辨率显示了（可以显示更多内容，就是字小点，但是很清楚），不过开机之前不能插外接显示器，如果开机之前插外接显示器的话，开机之后，本本和外接屏都是黑屏的。

另外，我更新了一下 Clover 到最新版，可以升级到 Big Sur，一切都正常，就是休眠之后唤醒黑屏，据说这个是 Big Sur 本身的 bug，就连 Macmini 白苹果都未能幸免，只能等 Big Sur 自己来解决这个问题。

**Comment by wqianglxf** [comment]
> > > @wqianglxf 怎么搞定的，我的 飞利浦 4K 显示器，现在接上去只能达到1080p，或者1080x2160这样一个奇怪分辨率。
> > 
> > 
> > 搞定没有？小马哥，你的这种情况可能是EDID的问题。我只是修改0x876 to 0x02，还有输入了正确的EDID。但我用了分辩率修改软件，强制修改到4K@30hz。这个修改有可能在黑屏的情况下，所有我用远程桌面试的，后来成功了。
> 
> 嗯，确实跟 EDID 有关，昨天我把 EDID 改了一下，0x876 也改为了 0x02，然后装了 SwitchResX ，外接显示器之后，确实可以正常 4K@30Hz 显示了，本本自带的屏幕也可以用更高的 HiDPI 分辨率显示了（可以显示更多内容，就是字小点，但是很清楚），不过开机之前不能插外接显示器，如果开机之前插外接显示器的话，开机之后，本本和外接屏都是黑屏的。
> 
> 另外，我更新了一下 Clover 到最新版，可以升级到 Big Sur，一切都正常，就是休眠之后唤醒黑屏，据说这个是 Big Sur 本身的 bug，就连 Macmini 白苹果都未能幸免，只能等 Big Sur 自己来解决这个问题。

666，Bigsur升级的是11.1吗？除了休眠后黑屏，其它的问题有吗，方便分享一下EFI 吗，小马哥，好激动。我的Mail: wqianglxf@tom.com

**Comment by andot** [comment]
> > > > @wqianglxf 怎么搞定的，我的 飞利浦 4K 显示器，现在接上去只能达到1080p，或者1080x2160这样一个奇怪分辨率。
> > > 
> > > 
> > > 搞定没有？小马哥，你的这种情况可能是EDID的问题。我只是修改0x876 to 0x02，还有输入了正确的EDID。但我用了分辩率修改软件，强制修改到4K@30hz。这个修改有可能在黑屏的情况下，所有我用远程桌面试的，后来成功了。
> > 
> > 
> > 嗯，确实跟 EDID 有关，昨天我把 EDID 改了一下，0x876 也改为了 0x02，然后装了 SwitchResX ，外接显示器之后，确实可以正常 4K@30Hz 显示了，本本自带的屏幕也可以用更高的 HiDPI 分辨率显示了（可以显示更多内容，就是字小点，但是很清楚），不过开机之前不能插外接显示器，如果开机之前插外接显示器的话，开机之后，本本和外接屏都是黑屏的。
> > 另外，我更新了一下 Clover 到最新版，可以升级到 Big Sur，一切都正常，就是休眠之后唤醒黑屏，据说这个是 Big Sur 本身的 bug，就连 Macmini 白苹果都未能幸免，只能等 Big Sur 自己来解决这个问题。
> 
> 666，Bigsur升级的是11.1吗？除了休眠后黑屏，其它的问题有吗，方便分享一下EFI 吗，小马哥，好激动。我的Mail: [wqianglxf@tom.com](mailto:wqianglxf@tom.com)

是的，是 11.1，晚上有时间的时候，我把它提交到 github 里面。到时候，你直接从 github 下载就行了。

**Comment by wqianglxf** [comment]
> > > > > @wqianglxf 怎么搞定的，我的 飞利浦 4K 显示器，现在接上去只能达到1080p，或者1080x2160这样一个奇怪分辨率。
> > > > 
> > > > 
> > > > 搞定没有？小马哥，你的这种情况可能是EDID的问题。我只是修改0x876 to 0x02，还有输入了正确的EDID。但我用了分辩率修改软件，强制修改到4K@30hz。这个修改有可能在黑屏的情况下，所有我用远程桌面试的，后来成功了。
> > > 
> > > 
> > > 嗯，确实跟 EDID 有关，昨天我把 EDID 改了一下，0x876 也改为了 0x02，然后装了 SwitchResX ，外接显示器之后，确实可以正常 4K@30Hz 显示了，本本自带的屏幕也可以用更高的 HiDPI 分辨率显示了（可以显示更多内容，就是字小点，但是很清楚），不过开机之前不能插外接显示器，如果开机之前插外接显示器的话，开机之后，本本和外接屏都是黑屏的。
> > > 另外，我更新了一下 Clover 到最新版，可以升级到 Big Sur，一切都正常，就是休眠之后唤醒黑屏，据说这个是 Big Sur 本身的 bug，就连 Macmini 白苹果都未能幸免，只能等 Big Sur 自己来解决这个问题。
> > 
> > 
> > 666，Bigsur升级的是11.1吗？除了休眠后黑屏，其它的问题有吗，方便分享一下EFI 吗，小马哥，好激动。我的Mail: [wqianglxf@tom.com](mailto:wqianglxf@tom.com)
> 
> 是的，是 11.1，晚上有时间的时候，我把它提交到 github 里面。到时候，你直接从 github 下载就行了。

期待中... 感谢小马哥！可以从10.15.7直接无损升级到bigsur11.1，还是说需要重新安装 Bigsur

**Comment by andot** [comment]
> > > > > > @wqianglxf 怎么搞定的，我的 飞利浦 4K 显示器，现在接上去只能达到1080p，或者1080x2160这样一个奇怪分辨率。
> > > > > 
> > > > > 
> > > > > 搞定没有？小马哥，你的这种情况可能是EDID的问题。我只是修改0x876 to 0x02，还有输入了正确的EDID。但我用了分辩率修改软件，强制修改到4K@30hz。这个修改有可能在黑屏的情况下，所有我用远程桌面试的，后来成功了。
> > > > 
> > > > 
> > > > 嗯，确实跟 EDID 有关，昨天我把 EDID 改了一下，0x876 也改为了 0x02，然后装了 SwitchResX ，外接显示器之后，确实可以正常 4K@30Hz 显示了，本本自带的屏幕也可以用更高的 HiDPI 分辨率显示了（可以显示更多内容，就是字小点，但是很清楚），不过开机之前不能插外接显示器，如果开机之前插外接显示器的话，开机之后，本本和外接屏都是黑屏的。
> > > > 另外，我更新了一下 Clover 到最新版，可以升级到 Big Sur，一切都正常，就是休眠之后唤醒黑屏，据说这个是 Big Sur 本身的 bug，就连 Macmini 白苹果都未能幸免，只能等 Big Sur 自己来解决这个问题。
> > > 
> > > 
> > > 666，Bigsur升级的是11.1吗？除了休眠后黑屏，其它的问题有吗，方便分享一下EFI 吗，小马哥，好激动。我的Mail: [wqianglxf@tom.com](mailto:wqianglxf@tom.com)
> > 
> > 
> > 是的，是 11.1，晚上有时间的时候，我把它提交到 github 里面。到时候，你直接从 github 下载就行了。
> 
> 期待中... 感谢小马哥！可以从10.15.7直接无损升级到bigsur11.1，还是说需要重新安装 Bigsur

我是无损升级的。只不过安装的时候，最后安装完黑屏了，然后等了一个多小时之后，听见风扇不呼呼转了，感觉已经装好了，就强制关机重启了，然后发现居然装好了。

**Comment by andot** [comment]
@wqianglxf 好了，我已经提交 pr 了，如果 @Azkali 还没有合并的话，你可以先从我的分支下载。

**Comment by wqianglxf** [comment]
> @wqianglxf 好了，我已经提交 pr 了，如果 @Azkali 还没有合并的话，你可以先从我的分支下载。

感谢，今天成功用您分享的EFI升级到Bigsur 11.1，升级过程中，没有出现什么异常。就是在登陆界面加载时，等了10分钟才出来。最后还是自动加载了。很开心！
升级后，我使用了一下，除了FCP外，我的软件没有重新安装。
出现的疑问：
1. 引导参数怎么全部没有了，是不需要，还是忘记了？
2. 之前我用的Intel Wifi驱动Airportitlwm无法使用，这个驱动适配方面比itlwm好用。Catalida时我成功加载，添加了IO80211Family，但升级后Wifi无法找到网络，如果加载IO80211Family，开机会卡住。求助！
3. 蓝牙方面，耳机可以，但鼠标连接上会自动断开，无法使用。之前以为升级后可以解决这个问题，没想到还是不可以。如果可以用上Airportitlwm的驱动，也许可以（Z490i台式机上我也是这个情况，但是用这个驱动，雷蛇鼠标连接上了）
