### ISSUE TITLE
no support at all

### ISSUE THREAD

**Issue by ghost** [Azkali/GPD-P2-MAX-Hackintosh#48]
Hi all
i tried to install that great hackintosh version
and found wired problems , first , the tutorial is not so tell exactly what to do , i barley understand what you want with the preparation of the usb and the clover step, 
also in the Clover Configurator there was a problem, (maybe version issue's)
the app isn't generate a serial number !
and also you tell "install driver's " but in the Clover Configurator. there is 2 section of drivers, i believe you want me to go for the kekxt !
and after driver (kekxt) installation the system won't come up again. its stuck on the apple load even it filled up all - - - ! this is the final step i got myself out of it and back to dual boot with windows and Ubuntu mate
but
since i read in the comment i realize that there is no support for touch screen with the 0.29 bios (no downgrade possible)

also the Bluetooth not work and the touchpad, 
the wifi work only if i click on the APP that provide the driver (not came with startup)

so, ill keep follow this interesting project but please make a good tutorial with pictures and arrows ! it not so easy to guess everything

**Comment by jschaeke** [comment]
Well I didn't had an all too bad experience installing it and using it as daily driver. Perhaps you can get help with specific issues in https://discord.gg/4jgssxG3 #gpdp2_max_general as I did receive some help back when I installed it. Personal opinion: if you start with hackintosh you need to be prepared to get your hands dirty; I wouldn't blame the owner of this repo as for us the installation instructions suffices.

BTW: Touchscreen works on bios 0.29 in macOS.
