### ISSUE TITLE
Lid sleep

### ISSUE THREAD

**Issue by clotted** [Azkali/GPD-P2-MAX-Hackintosh#5]
Tested your recent commit for "Added Lid and power button Sleep/Wake" 
Power button sleep works, but closing the lid does nothing.
Am I missing something?

GPD P2 Max - Batch 2 | BIOS 0.25 - macOS 10.15.1

**Comment by Azkali** [comment]
This seems to be related with the version 10.15.1, with the previous version of Catalina this was working

**Comment by clotted** [comment]
If putting into sleep manually (sometimes sleeps, sometimes wakes up seconds after) then close lid (if still in sleep state), then upon open lid it triggers wake. Very curious

**Comment by Azkali** [comment]
Could you send me your DSDT / SSDT files to compare with against the patch ?

**Comment by clotted** [comment]
Hope this is what you need:
[origin.zip](https://github.com/Azkali/GPD-P2-MAX-Hackintosh/files/3848502/origin.zip)

**Comment by clotted** [comment]
Did you find anything on this? Let me know if I can provide further info

**Comment by juniorlemos84** [comment]
> Hope this is what you need:
> [origin.zip](https://github.com/Azkali/GPD-P2-MAX-Hackintosh/files/3848502/origin.zip)

Hi Clotted! Would you mind sharing your patched folder? I can't get battery status. I've tried with both DSDT files provided by Azkali, but had no luck.
Thx

**Comment by clotted** [comment]
> ”I can't get battery status”

Sounds like different issue to that raised. I suggest checking issue #7

**Comment by Azkali** [comment]
@clotted Issue might be related to connected HID devices, check if disconnecting ( Bluetooth and USB ) devices solves the issue, I'll also investigate that by myself too

**Comment by Azkali** [comment]
Alright I can confirm this issue is related to devices being connected to the P2 MAX ( Batch 1 | BIOS 0.25 | 10.5.2 ) when no device is connected, lid sleep is working

**Comment by Azkali** [comment]
Solved by commit 5fd1075
