### ISSUE TITLE
battery not displayed

### ISSUE THREAD

**Issue by digitxo** [Azkali/GPD-P2-MAX-Hackintosh#7]
If I attempt to check the battery toggle in preferences it just automatically unchecks.

**Comment by clotted** [comment]
I had the same. Did you try as per readme:
“Battery Status ( patch differs if you have a 1st batch or 2nd batch GPD P2 MAX, if you have the 2nd batch remove DSDT.aml, and rename DSDT_2.aml as DSDT.aml )”

**Comment by digitxo** [comment]
tried that didn't work

**Comment by clotted** [comment]
Maybe worth trying a kextcache rebuild and reboot.
I used Hackintool:
https://www.tonymacx86.com/threads/release-hackintool-v2-8-6.254559/

**Comment by digitxo** [comment]
I don't see a kextcache rebuild feature?

**Comment by clotted** [comment]
> I don't see a kextcache rebuild feature?

Tools > Rebuild Kextcache ....
![](https://floppyblog.com/wp-content/uploads/2019/10/Screenshot-2019-10-10-at-3.46.50-PM.png)

**Comment by Azkali** [comment]
I think it's better to let clover inject the kexts, the patch should work with Mojave and Catalina but only for BIOS 0.24/0.25 !
Previous BIOS are not compatible with the patch.

**Comment by digitxo** [comment]
Updated BIOS. Fixed the problem. Thanks Azkali! What are the chances of getting touchscreen working?
