### ISSUE TITLE
Touchscreen possible?

### ISSUE THREAD

**Issue by clotted** [Azkali/GPD-P2-MAX-Hackintosh#8]
Adding for info, apparently is possible.
May be worth investigating for the P2 Max:
https://www.tonymacx86.com/threads/hp-spectre-x360-15-2017-i2c-touchscreen-and-pen-working-in-osx.246052/

**Comment by Azkali** [comment]
Sure, I will investigate the possibility to add it thanks !

**Comment by PeterCxy** [comment]
It seems like that the HP Spectre X360 only works because its touchscreen is an I2C HID device, while ours on P2 MAX is a Goodix model that is I2C but not HID, that requires separate driver (in Linux it is `drivers/input/touchscreen/goodix.c`). So this would probably not work unless someone decides to port the driver to macOS.

**Comment by Azkali** [comment]
Closing due to possible driver issue.

**Comment by Azkali** [comment]
Adding this issue for reference as CHUWI Minibook uses the same Touchscreen [here](https://github.com/THEDEVIOUS1/CHUWI-MINIBOOK-HACKINTOSH/issues/6)

**Comment by lazd** [comment]
Hey @Azkali, I wrote a driver for the Goodix touchscreen, [VoodooI2CGoodix](https://github.com/lazd/VoodooI2CGoodix/). Give the kext a try and see if it works for your P2 MAX! You will need VoodooI2C.kext 2.3.

See [the README](https://github.com/lazd/VoodooI2CGoodix#installation) for installation, usage, and support information, and head over to [releases](https://github.com/lazd/VoodooI2CGoodix/release) to download the kext. Cheers!

**Comment by Azkali** [comment]
Thanks @lazd I've just added your driver and updated this repo 
Solved by c2b0c5f

**Comment by lazd** [comment]
@Azkali excellent! I will update my driver to match the `GDIX1002` device properly so you don't have to patch the plist.

**Comment by lazd** [comment]
@Azkali [VoodooI2CGoodix 0.3.0](https://github.com/lazd/VoodooI2CGoodix/releases/tag/v0.3.0) should work without modification to the plist, and now has stylus support!
