### ISSUE TITLE
FYI: Brightnes control not working unless using AppleBacklightFixup

### ISSUE THREAD

**Issue by PeterCxy** [Azkali/GPD-P2-MAX-Hackintosh#9]
I'm not sure if it's just me using new BIOS (0.27) that broke things, but it looks like that for me the current configuration in this repository cannot enable brightness control in Catalina 10.15.1, while the README.md claimed it to be working fine. Using `AppleBacklightFixup` (https://bitbucket.org/RehabMan/applebacklightfixup/) with its version of `SSDT-PNLF.aml` fixed it for me (without its version of the ACPI patch it won't work either), so I'm posting here just in case you would include this or anyone runs into the same issue

**Comment by Azkali** [comment]
Thanks for the info, it's indeed a problem with bios 0.27

**Comment by Azkali** [comment]
If anyone encounters this issue, please checkout commit ce064ec
